import { PHASE_OPTIONS } from './constants'

export const isDemo = typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('demo') === '1'

export const demoPeople = [
  { id: 'p-1', name: 'Zhang Wei', email: 'zhang.wei@lenovo.com', team_group: 'Regular Team' },
  { id: 'p-2', name: 'Li Na', email: 'li.na@lenovo.com', team_group: 'Regular Team' },
  { id: 'p-3', name: 'Wang Jun', email: 'wang.jun@lenovo.com', team_group: 'ISS Team' },
  { id: 'p-4', name: 'Chen Fang', email: 'chen.fang@lenovo.com', team_group: 'Regular Team' },
  { id: 'p-5', name: 'Liu Qiang', email: 'liu.qiang@lenovo.com', team_group: 'ISS Team' },
]

export const demoWhitelist = [
  { email: 'zhang.wei@lenovo.com', active: true },
  { email: 'li.na@lenovo.com', active: true },
  { email: 'wang.jun@lenovo.com', active: true },
  { email: 'chen.fang@lenovo.com', active: true },
  { email: 'liu.qiang@lenovo.com', active: false },
]

export const demoProjects = [
  {
    id: 'pr-1',
    name: 'Vetra Platform Rollout',
    description: 'Company-wide rollout of the Vetra project management platform, replacing the legacy tracking system.',
    biz_group: 'IDG',
    biz_focal: 'Amy Zhou',
    it_focal: 'Kevin Wu',
    dt_focal_id: 'p-1,p-2',
    funding_type: 'R&D',
    budget: 500000,
    budget_status: 'Approved',
    vetra_adopted: 'Yes',
    current_phase: 'SIT/UAT/MTP',
    overall_status: 'On Track',
    start_date: '2026-01-15',
    end_date: '2026-12-31',
    biz_benefit: 'Cost saving: cut status-reporting effort ~20%; HC saving: avoid adding 1 FTE for legacy tracker maintenance; operational efficiency: single source of project status.',
    progress: '<div>Completed <b>SIT</b> for all core modules; started <span style="color:#0070c0">UAT</span> with business on the finance module.</div>',
    next_steps: '<div>UAT sign-off for remaining modules by <b>Aug 15</b>; start MTP rehearsal.</div>',
    blockers: '<div>Blocked: UAT test data depends on vendor — awaiting <span style="background:#ffff00">ERP data refresh</span>.</div>',
    eta: '2026-08-20',
    owner: 'Zhang Wei',
    updates_updated_at: '2026-08-03T09:00:00Z',
    last_update: {
      progress: '<div>Finished DEV module integration; SIT entry checklist approved.</div>',
      next_steps: 'Start SIT execution, resolve interface defects.',
      blockers: '<div>None</div>',
      eta: '2026-08-05',
      owner: 'Zhang Wei',
      updated_at: '2026-07-28T10:00:00Z',
    },
    created_at: '2026-01-15T02:00:00Z',
  },
  {
    id: 'pr-2',
    name: 'Vendor Onboarding Automation',
    description: 'Automate the vendor onboarding workflow for procurement and finance approvals.',
    biz_group: 'ISG',
    biz_focal: 'Grace Liu',
    it_focal: 'Tom Chen',
    dt_focal_id: 'p-3',
    funding_type: 'Vendor Onboarding',
    budget: 200000,
    budget_status: 'Ongoing',
    vetra_adopted: 'Yes',
    current_phase: 'Budget Application',
    overall_status: 'Caution',
    start_date: '2026-03-01',
    end_date: '2026-11-30',
    biz_benefit: 'Man-hour saving: cut onboarding cycle from 10 to 4 days; cost avoidance: fewer procurement admin hours; accuracy: fewer manual data-entry errors.',
    progress: '<div>ROI analysis drafted; pending <b>senior management review</b>.</div>',
    next_steps: '<div>Submit budget approval package; confirm funding envelope.</div>',
    blockers: '<div>Risk: funding cap may be reduced in the next planning cycle.</div>',
    eta: '2026-09-10',
    owner: 'Wang Jun',
    updates_updated_at: '2026-08-02T14:00:00Z',
    last_update: null,
    created_at: '2026-03-01T02:00:00Z',
  },
  {
    id: 'pr-3',
    name: 'DevOps Toolchain Integration',
    description: 'Evaluate and integrate a unified DevOps toolchain for the delivery teams.',
    biz_group: 'SSG',
    biz_focal: 'Mia Yang',
    it_focal: 'Alex Hu',
    dt_focal_id: 'p-4,p-5',
    funding_type: 'R&D AI',
    budget: 150000,
    budget_status: 'Draft',
    vetra_adopted: 'No',
    current_phase: 'FEASIBILITY',
    overall_status: 'Not Started',
    start_date: '2026-05-10',
    end_date: '2027-03-31',
    biz_benefit: 'Operational efficiency: less rework across teams; cost saving: lower tool license cost; technical accuracy: unified build & release metrics.',
    progress: '<div>Feasibility study kicked off; evaluating <b>3 tool vendors</b>.</div>',
    next_steps: '<div>Complete vendor scoring matrix; draft recommendation for review.</div>',
    blockers: '',
    eta: '2026-08-30',
    owner: 'Chen Fang',
    updates_updated_at: '2026-08-01T08:00:00Z',
    last_update: {
      progress: 'Project chartered; initial requirements collected.',
      next_steps: 'Shortlist vendors and schedule demos.',
      blockers: '',
      eta: '2026-08-30',
      owner: 'Chen Fang',
      updated_at: '2026-07-25T08:00:00Z',
    },
    created_at: '2026-05-10T02:00:00Z',
  },
  {
    id: 'pr-4',
    name: 'Order Management Enhancement',
    description: 'Go-live of the enhanced order management flow with new approval routing.',
    biz_group: 'IDG',
    biz_focal: 'Amy Zhou',
    it_focal: 'Kevin Wu',
    dt_focal_id: 'p-1',
    funding_type: 'BAU',
    budget: 120000,
    budget_status: 'Approved',
    vetra_adopted: 'Yes',
    current_phase: 'Go-live',
    overall_status: 'On Track',
    start_date: '2026-02-20',
    end_date: '2026-08-31',
    biz_benefit: 'Faster order turnaround; fewer approval delays; improved customer satisfaction — CSAT target 85+.',
    progress: '<div>Production deployment completed; hypercare active. <span style="background:#ffff00">Cut-over finished on schedule</span>.</div>',
    next_steps: '<div>Monitor hypercare; close out known defects from the first release.</div>',
    blockers: '',
    eta: '2026-07-30',
    owner: 'Zhang Wei',
    updates_updated_at: '2026-07-29T16:00:00Z',
    last_update: {
      progress: '<div>Pre-go-live checklist <b>100%</b> complete; roll-back plan approved.</div>',
      next_steps: 'Final dress rehearsal; change request approval.',
      blockers: '<div>None</div>',
      eta: '2026-07-28',
      owner: 'Zhang Wei',
      updated_at: '2026-07-22T16:00:00Z',
    },
    created_at: '2026-02-20T02:00:00Z',
  },
  {
    id: 'pr-5',
    name: 'Legacy Reporting Decommission',
    description: 'Decommission the legacy reporting system after migration to the new platform.',
    biz_group: 'ISG',
    biz_focal: 'Grace Liu',
    it_focal: 'Tom Chen',
    dt_focal_id: 'p-3',
    funding_type: 'R&D',
    budget: 0,
    budget_status: 'Draft',
    vetra_adopted: 'No',
    current_phase: 'Post-Go-live / Closure',
    overall_status: 'Finished',
    start_date: '2025-11-01',
    end_date: '2026-06-30',
    biz_benefit: 'Cost avoidance: retire legacy reporting licenses; lower maintenance cost; reusability: single reporting platform for all teams.',
    progress: '<div>Retrospective completed; <b>project closed</b> and resources released.</div>',
    next_steps: '<div>Archive project documents; hand over maintenance to operations.</div>',
    blockers: '',
    eta: '2026-06-30',
    owner: 'Wang Jun',
    updates_updated_at: '2026-06-28T10:00:00Z',
    last_update: null,
    created_at: '2025-11-01T02:00:00Z',
  },
]

export function demoPhaseOptions() {
  const custom = [...new Set(demoProjects.map(p => p.current_phase).filter(Boolean))]
    .filter(p => !PHASE_OPTIONS.includes(p))
  return [...PHASE_OPTIONS, ...custom]
}
